spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luo_p?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: adminLp
    username: root
mybatis:
  mapper-locations: classpath:mapper/*
